name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # Setup virtual env, install dependencies
      - name: Create new virtual env and activate it
        run: |
          working-directory: ~/kontan/kontan-server
          npm install
          npm run build
  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      # Kill gunicorn server, if running already
      - name: Restart services
        run: |
          sudo killall node
          sudo killall ngrok
          sudo supervisorctl restart kontan:*