name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-install:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      # Setup virtual env, install dependencies
      - name: Create new virtual env and activate it
        working-directory: /home/kontan/kontan-server
        run: |
          npm install
          npm run build
          sudo killall node
          sudo killall ngrok
          sudo supervisorctl restart kontan:*