name: Deploy
on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: '~/kontan/kontan-server/'


jobs:
  build-and-install:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          path: ~/kontan
      # Setup virtual env, install dependencies
      - name: Create new virtual env and activate it
        run: |
          npm install
          npm run build

      - name: Restart and run
        run: |
          echo "export PATH="$(npm config get prefix)"/bin/node:$PATH" > startProd.sh
          { echo "cd "$(pwd)""; echo "npm run serve:prod"; } >> startProd.sh
          echo "sudo killall ngrok" > startProd.tunnel.sh
          echo "ngrok http --config=$HOME/.config/ngrok/ngrok.yml --subdomain=kontan localhost:3000 --log=stdout > /var/log/ngrok.prod.log" >> startProd.tunnel.sh
          sudo supervisorctl restart kontan:*
